### PR TITLE
add first part of set_value to the xmi

### PR DESCRIPTION
**Pull request by mjr-deltares**
Other types and tests for scalar and >1-dim will follow. This depends on PR 577 at MODFLOW6

### CODE REVIEW

**Comment by mjr-deltares** [comment]
Hi @jdhughes-usgs, maybe we can look at this together so I can explain you what I have been doing here. This relates to my latest PR in MODFLOW: https://github.com/MODFLOW-USGS/modflow6/pull/577

**Comment by jdhughes-usgs** [comment]
@mjr-deltares When? Tomorrow or today?

**Comment by mjr-deltares** [comment]
Tomorrow would be great, could be part of our planned meeting

**Comment by jdhughes-usgs** [comment]
@mjr-deltares ok...remember I may be a little late tomorrow

**Review by Hofer-Julian — APPROVED** [review]

**Pull request merged**
